// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.QuangTNV.Models;

public partial class CoursesQuangTnv
{
    public int CourseIdquangTnv { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string AgeGroup { get; set; }

    public string Category { get; set; }

    public int DurationInMinutes { get; set; }

    public string InstructorName { get; set; }

    public string ContentUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public string LearningObjectives { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool IsActive { get; set; }

    public int? ViewCount { get; set; }

    public decimal? Rating { get; set; }

    public string DifficultyLevel { get; set; }

    public virtual ICollection<UserCoursesQuangTnv> UserCoursesQuangTnvs { get; set; } = new List<UserCoursesQuangTnv>();
}