// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.QuangTNV.Models;

public partial class UserCoursesQuangTnv
{
    public int UserCourseIdquangTnv { get; set; }

    public int UserId { get; set; }

    public int CourseId { get; set; }

    public DateTime EnrollmentDate { get; set; }

    public DateTime? CompletionDate { get; set; }

    public decimal? Progress { get; set; }

    public int? Score { get; set; }

    public bool? CertificateIssued { get; set; }

    public string CertificateUrl { get; set; }

    public DateTime? LastAccessDate { get; set; }

    public string Feedback { get; set; }

    public int? Rating { get; set; }

    public virtual CoursesQuangTnv Course { get; set; }

    public virtual SystemUserAccount User { get; set; }
}